name: Go CI with Docker and PostgreSQL

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Run Tests
        run: go test ./...

      - name: Lint
        run: go vet ./...

      - name: Build Docker image
        run: |
          docker build --cache-from=type=local,src=/tmp/.buildx-cache \
                       --cache-to=type=local,dest=/tmp/.buildx-cache \
                       -t ${{ secrets.USERNAME }}/gopost:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login --username "${{ secrets.USERNAME }}" --password-stdin
          docker push ${{ secrets.USERNAME }}/gopost:latest
